<a href="https://colab.research.google.com/github/arun-84/sample/blob/master/class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
node1=tf.constant(5.0,tf.float32)
node2=tf.constant(4.0,tf.float32)
print(node1,node2)
with tf.Session() as sess:
  print(sess.run(node1))
firstNode=tf.constant("hello")
secondNode=tf.constant("world")
with tf.Session() as sess:
  print(sess.run(firstNode+ secondNode))
firstMatrix=tf.constant([[1,2],[3,4]])
secondMatrix=tf.constant([[1,2],[3,4]])
with tf.Session() as sess:
  print(sess.run(firstMatrix*secondMatrix)) 
a=firstMatrix.get_shape()
print(a)
with tf.Session() as sess:
  print(sess.run(tf.matmul(firstMatrix,secondMatrix)))
fillMatrix=tf.fill((4,4),10)
myZeroMatrix=tf.zeros((4,4))
myOnesMatrix=tf.ones((4,4))
myrandN=tf.random_normal((4,4),mean=0,stddev=1.0)
myrandU=tf.random_uniform((4,4),minval=0,maxval=1.0)
ops=[fillMatrix,myZeroMatrix,myOnesMatrix, myrandN,myrandU]
sess=tf.InteractiveSession()
for op in ops:
  print(op.eval())
  print('\n')

Tensor("Const_75:0", shape=(), dtype=float32) Tensor("Const_76:0", shape=(), dtype=float32)
5.0
b'helloworld'
[[ 1  4]
 [ 9 16]]
(2, 2)
[[ 7 10]
 [15 22]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.8207956  -1.4257153   0.73471767 -0.06226844]
 [ 0.8443487  -0.49526322  0.4901379  -0.60374635]
 [-0.2194347   0.21501121 -1.4145557  -0.68505913]
 [-0.18295336  2.4042027   0.7197361  -0.4887133 ]]


[[0.51969695 0.5463486  0.78168905 0.76685464]
 [0.9870875  0.66081846 0.64211726 0.28485835]
 [0.20795405 0.6551423  0.37610173 0.7726058 ]
 [0.42760563 0.63445807 0.9985446  0.03458536]]




/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1761: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
