<a href="https://colab.research.google.com/github/arun-84/sample/blob/master/tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
hello=tf.constant("hello")
world=tf.constant("world")
sess=tf.Session()
print(sess.run(hello+world))
sess.close()
with tf.Session() as sess:
  print(sess.run(hello+world))
a=tf.constant(30)
b=tf.constant(20)
with tf.Session() as sess:
  print (sess.run(a+b))
fill_mat=tf.fill((4,4),10)
myzeroMatrix=tf.zeros((4,4))
myonesMatrix=tf.zeros((4,4))
myrandNormal=tf.random_normal((4,4),mean=0,stddev=1)
myrandUniform=tf.random_uniform((4,4),minval=0,maxval=1)
ops=[fill_mat,myzeroMatrix,myonesMatrix,myrandNormal,myrandUniform]
sess=tf.InteractiveSession()
for op in ops:
  print(sess.run(op))
  print('\n')

firstMatrix=tf.constant([[1,2],[3,4]])
firstMatrix.get_shape()
secondMatrix=tf.constant([[10],[2]])
result=tf.matmul(firstMatrix,secondMatrix)
sess.run(result)


b'helloworld'
b'helloworld'
50
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-1.3670233   1.6530567   0.75166494 -0.01219022]
 [ 0.7447083   0.25929835 -0.5472847  -1.3153809 ]
 [ 0.5006023  -1.0765946   1.5253875   0.87453353]
 [ 0.34863362  0.21888521 -0.87007403  0.18255438]]


[[0.19414616 0.9112159  0.69884896 0.14967668]
 [0.87558734 0.48462558 0.69098806 0.19500864]
 [0.45281434 0.18554497 0.7020359  0.54706955]
 [0.978204   0.5942514  0.7225158  0.4646697 ]]




/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1761: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


array([[14],
       [38]], dtype=int32)

In [ ]:
a+b


<tf.Tensor 'add_7:0' shape=() dtype=int32>