<a href="https://colab.research.google.com/github/arun-84/sample/blob/master/tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
hello=tf.constant("hello")
world=tf.constant("world")
sess=tf.Session()
print(sess.run(hello+world))
sess.close()
with tf.Session() as sess:
  print(sess.run(hello+world))
a=tf.constant(30)
b=tf.constant(20)
with tf.Session() as sess:
  print (sess.run(a+b))
fill_mat=tf.fill((4,4),10)
myzeroMatrix=tf.zeros((4,4))
myonesMatrix=tf.zeros((4,4))
myrandNormal=tf.random_normal((4,4),mean=0,stddev=1)
myrandUniform=tf.random_uniform((4,4),minval=0,maxval=1)
ops=[fill_mat,myzeroMatrix,myonesMatrix,myrandNormal,myrandUniform]
sess=tf.InteractiveSession()
for op in ops:
  print(sess.run(op))
  print('\n')

b'helloworld'
b'helloworld'
50
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.50741696 -1.306248    1.4086671   1.2783431 ]
 [ 1.0039356   1.2680905  -0.601396    0.13804401]
 [-1.2135493  -0.8563051   0.4771601  -0.19518104]
 [-0.04214834  1.8539706   0.10735975 -1.2370887 ]]


[[0.17563069 0.06318069 0.15640211 0.95970285]
 [0.49656057 0.309842   0.7014389  0.6456535 ]
 [0.301394   0.43733037 0.70713925 0.09604895]
 [0.31921554 0.92938125 0.19007218 0.782593  ]]




/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1761: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [9]:
a+b


<tf.Tensor 'add_7:0' shape=() dtype=int32>